// Sales
export const GET_SALES_FULFILLED = 'GET_SALES_FULFILLED';
export const GET_SALES_PENDING = 'GET_SALES_PENDING';
export const GET_SALES_REJECTED = 'GET_SALES_REJECTED';
export const SALES_SHOULD_FETCH = 'SALES_SHOULD_FETCH';

// Settings
export const SETTINGS_UPDATE = 'SETTINGS_UPDATE';
export const PREVPATH_UPDATE = 'PREVPATH_UPDATE';

// Summary User
export const USER_SHOULD_FETCH = 'USER_SHOULD_FETCH';

export const GET_USER_FULFILLED = 'GET_USER_FULFILLED';
export const GET_USER_PENDING = 'GET_USER_PENDING';
export const GET_USER_REJECTED = 'GET_USER_REJECTED';

// Summary
export const SHOULD_FETCH_SUMMARY = 'SHOULD_FETCH_SUMMARY';
export const SHOULD_FETCH_SALES = 'SHOULD_FETCH_SALES';
export const SHOULD_FETCH_TEMPLATES = 'SHOULD_FETCH_TEMPLATES';

// Summary Account
export const GET_USER_ACCOUNT_FULFILLED = 'GET_USER_ACCOUNT_FULFILLED';
export const GET_USER_ACCOUNT_PENDING = 'GET_USER_ACCOUNT_PENDING';
export const GET_USER_ACCOUNT_REJECTED = 'GET_USER_ACCOUNT_REJECTED';

// Summary Earnings
export const GET_USER_EARNINGS_FULFILLED = 'GET_USER_EARNINGS_FULFILLED';
export const GET_USER_EARNINGS_PENDING = 'GET_USER_EARNINGS_PENDING';
export const GET_USER_EARNINGS_REJECTED = 'GET_USER_EARNINGS_REJECTED';

// Templates
export const GET_TEMPLATE_FULFILLED = 'GET_TEMPLATE_FULFILLED';
export const GET_TEMPLATE_PENDING = 'GET_TEMPLATE_PENDING';
export const GET_TEMPLATE_REJECTED = 'GET_TEMPLATE_REJECTED';
export const TEMPLATE_SHOULD_FETCH = 'TEMPLATE_SHOULD_FETCH';

// USER
export const SET_USER_AUTH = 'SET_USER_AUTH';
export const SET_USER_AUTH_PENDING = 'SET_USER_AUTH_PENDING';
export const SET_USER_FOLLOWERS = 'SET_USER_FOLLOWERS';
export const SET_USER_SALES = 'SET_USER_SALES';
